<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class AdminStatsController extends Controller
{
    // Return cached dashboard snapshot (generated by artisan command)
    public function index(Request $request)
    {
        $path = 'dashboard.json';
        if (!Storage::disk('local')->exists($path)) {
            return response()->json(['message' => 'Snapshot not ready. Run artisan dashboard:generate or wait for scheduler.'], 503);
        }

        $json = Storage::disk('local')->get($path);
        $data = json_decode($json, true);
        return response()->json($data);
    }
}
