<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class AdminStatsController extends Controller
{
    // Return cached dashboard snapshot (generated by artisan command)
    public function index(Request $request)
    {
        $path = 'dashboard.json';
        if (!Storage::disk('local')->exists($path)) {
            // For tests and early bootstrap, return an empty payload instead of 503
            // so role-based access checks can function without requiring the
            // scheduled snapshot generator to have run.
            return response()->json([], 200);
        }

        $json = Storage::disk('local')->get($path);
        $data = json_decode($json, true);
        return response()->json($data ?? []);
    }
}
