name: CI

on:
  push:
    branches: [ main, feat/**, "**" ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, intl, pdo_mysql, pdo_sqlite
          coverage: none

      - name: Use Node (for front-end tooling if needed)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache composer
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install composer dependencies
        working-directory: backend
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Prepare environment
        working-directory: backend
        run: |
          cp .env.example .env || true
          php artisan key:generate || true

      - name: Prepare sqlite database for tests
        working-directory: backend
        run: |
          # Use SQLite in-memory for CI tests to avoid depending on external DB service
          cp .env.example .env || true
          php artisan key:generate || true

      - name: Run migrations (sqlite in-memory)
        working-directory: backend
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ':memory:'
        run: php artisan migrate --force

      - name: Run phpunit (sqlite in-memory)
        working-directory: backend
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ':memory:'
        run: vendor/bin/phpunit --testdox
